name: EntityAnalyzer
version: 1.3
api-version: 1.15
description: EntityAnalyzer
author: kubotan
website: https://gorogoro.space/
main: space.gorogoro.entityanalyzer.EntityAnalyzer

commands:
  eastatus:
    description: Ranking world entities type
    usage: /<command>
  eatwrank:
    description: Ranking world tile entities
    usage: /<command>
  eawrank:
    description: Ranking world entities
    usage: /<command>
  earank:
    description: Ranking Entity
    usage: /<command> <world_name> <limit>
  eatrank:
    description: Ranking Tile All
    usage: /<command> <world_name> <limit>
  eathrank:
    description: Ranking Tile Hopper
    usage: /<command> <world_name> <limit>
  ealimits:
    description: Show Chank Entity Limits
    usage: /<command> <world_name> <limit>
  ealimitset:
    description: Set Entity/Chank Limits
    usage: /<command> <world_name string> <limit int>
  eanear:
    description: Check Near Chunk
    usage: /<command>